### PR TITLE
Upgraded to Angular 6 and fixed for Bootstrap 4 support

### PR DESCRIPTION
**Pull request by joelmuskwe**
Upgraded to Angular 6 and fixed for Bootstrap 4 support

### CODE REVIEW

**Comment by joelmuskwe** [comment]
will try to work on updating the readme file next

**Comment by third774** [comment]
Awesome. I'm working on bringing my bootstrap 4 support changes in. Looks like the CI stuff is still broken too. Hopefully we can get a release out soon.

**Comment by joelmuskwe** [comment]
would love to assist you with the CI stuff if possible still trying to get used to travis. if possible if you could email me on joelmuskwe@gmail.com on how you CI is setup would really like to take a look at it too.

**Comment by joelmuskwe** [comment]
will do hey.

**Pull request closed without merging**
